/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fckylkeiftgwnbbsmwiz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZja3lsa2VpZnRnd25iYnNtd2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODU4NTIsImV4cCI6MjA3MjE2MTg1Mn0.yYzcTOyFynN1lTKVMg97LhwCsHCvt-sndixYjEq-4jw"